# Generated by Django 3.0.4 on 2020-04-22 04:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200422_1103'),
        ('users', '0007_auto_20200422_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 4, 3, 41, 33921, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ItemSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='items_ordered',
            field=models.ManyToManyField(to='users.ItemSelection'),
        ),
    ]
