# Generated by Django 3.0.4 on 2020-04-22 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200422_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 4, 19, 7, 502132, tzinfo=utc)),
        ),
    ]
