# Generated by Django 3.0.4 on 2020-04-22 04:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200422_1103'),
        ('users', '0010_auto_20200422_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemselection',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 4, 39, 7, 671184, tzinfo=utc)),
        ),
    ]
