# Generated by Django 3.0.4 on 2020-04-22 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200422_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 16, 1, 55, 544688, tzinfo=utc)),
        ),
    ]
