# Generated by Django 3.0.4 on 2020-05-28 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200528_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 28, 11, 11, 20, 344416, tzinfo=utc)),
        ),
    ]
