# Generated by Django 3.0.4 on 2020-05-29 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200529_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 9, 4, 21, 111551, tzinfo=utc)),
        ),
    ]
