# Generated by Django 3.0.4 on 2020-06-06 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200601_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 3, 34, 46, 576646, tzinfo=utc)),
        ),
    ]
