# Generated by Django 2.2.13 on 2020-06-22 01:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200622_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 1, 33, 4, 453778, tzinfo=utc)),
        ),
    ]
