# Generated by Django 2.2.13 on 2020-06-22 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200622_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 1, 59, 32, 482288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Processing'), ('S', 'Shipping'), ('C', 'Completed'), ('RC', 'Requesting Cancel'), ('AC', 'Accepted Cancellation Request')], default='P', max_length=2),
        ),
    ]
