# Generated by Django 2.2.13 on 2020-06-22 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200622_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 2, 56, 8, 739060, tzinfo=utc)),
        ),
    ]
