# Generated by Django 2.2.13 on 2020-06-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200622_0956'),
        ('users', '0026_auto_20200620_2231'),
    ]

    operations = [
    ]
