# Generated by Django 2.2.13 on 2020-06-25 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200625_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 23, 53, 875177, tzinfo=utc)),
        ),
    ]
