# Generated by Django 2.2.13 on 2020-06-25 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200625_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 42, 40, 853971, tzinfo=utc)),
        ),
    ]
