# Generated by Django 2.2.13 on 2020-06-25 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20200626_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 17, 12, 25, 406621, tzinfo=utc)),
        ),
    ]
