# Generated by Django 2.2.13 on 2020-06-28 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20200626_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 4, 54, 58, 983414, tzinfo=utc)),
        ),
    ]
