# Generated by Django 2.2.13 on 2020-06-28 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20200628_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 5, 13, 10, 759545, tzinfo=utc)),
        ),
    ]
