# Generated by Django 3.0.4 on 2020-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
    ]
