# Generated by Django 3.0.4 on 2020-04-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_product.jpg', upload_to='product_pics'),
        ),
    ]
