# Generated by Django 3.0.4 on 2020-05-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200422_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
        migrations.AddField(
            model_name='item',
            name='number_item_left',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
