# Generated by Django 3.0.4 on 2020-05-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200528_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dimension',
            field=models.CharField(default='? x ? x ? cm', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
