# Generated by Django 3.0.4 on 2020-06-06 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200606_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
