# Generated by Django 2.2.13 on 2020-06-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200606_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stop_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='topic',
            field=models.CharField(default='', max_length=30),
        ),
    ]
