# Generated by Django 2.2.13 on 2020-06-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200626_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='topic',
            field=models.CharField(choices=[('W', 'Wedding'), ('B', 'Birthday'), ('P', 'Party'), ('V', 'Valentine'), ('T', 'Tet')], default=None, max_length=2, null=True),
        ),
    ]
