# Generated by Django 2.2.13 on 2020-06-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200626_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic.Topic'),
        ),
    ]
