# Generated by Django 2.2.13 on 2020-06-26 02:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200626_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('brief', models.TextField()),
                ('background', models.ImageField(upload_to='blog_background')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
