# Generated by Django 2.2.13 on 2020-06-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
